name: blockchain-restful-address-index-server
version: '0.2.0.0'
synopsis: Server for RESTful HTTP "addr-index bitcoind" wrapper
description: See README.md
category: Bitcoin,Web
author: Rune K. Svendsen
maintainer: runesvend@gmail.com
license: OtherLicense
license-file: LICENSE
github: runeksvendsen/blockchain-restful-address-index-server


default-extensions:
- RecordWildCards
- OverloadedStrings

dependencies:
- blockchain-restful-address-index-api
- base16-bytestring
- text
- string-conversions
- haskoin-core
- aeson
- servant
- http-api-data
- http-media
- errors
- cereal
- hexstring
- base >=4 && <5
- bitcoin-types
- bitcoin-tx
- bitcoin-api
- base58string
- bytestring
- mtl
- transformers
- configurator
- either
- servant-server
- http-client
- wai
- warp


library:
  source-dirs: src
  ghc-options: -W

executables:
  rest-addr:
    dependencies:
    - blockchain-restful-address-index-server
    main: Main.hs
    source-dirs: driver
    ghc-options:
    - -W
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -dcore-lint
    - -debug
